### ISSUE TITLE
ASAN: container-overflow when linking with static library

### ISSUE THREAD

**Issue by gabyx** [rttrorg/rttr#222]
I have some weird container-overflow when linking with `RTTR:Core_Lib` (static lib) which does not happen when linking to `RTTR:Core`.

Can you make any sense of why this is happening (see the ASAN report below) ->  `rttr::detail::type_data` ??
Static initialization stuff??

```cpp
gui/executionGraphGui/server/ExecutionGraphServer
=================================================================
==2662==ERROR: AddressSanitizer: container-overflow on address 0x6030000001a8 at pc 0x00000062de91 bp 0x7fff9d9b12f0 sp 0x7fff9d9b12e8
READ of size 8 at 0x6030000001a8 thread T0
    #0 0x62de90 in std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >::release() /usr/local/opt/llvm-7.0/bin/../include/c++/v1/memory:2624:26
    #1 0x62de90 in std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >::unique_ptr(std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >&&) /usr/local/opt/llvm-7.0/bin/../include/c++/v1/memory:2477
    #2 0x62de90 in void std::__1::allocator<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> > >::construct<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >, std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> > >(std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >*, std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >&&) /usr/local/opt/llvm-7.0/bin/../include/c++/v1/memory:1811
    #3 0x62de90 in void std::__1::allocator_traits<std::__1::allocator<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> > > >::__construct<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >, std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> > >(std::__1::integral_constant<bool, true>, std::__1::allocator<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> > >&, std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >*, std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >&&) /usr/local/opt/llvm-7.0/bin/../include/c++/v1/memory:1716
    #4 0x62de90 in void std::__1::allocator_traits<std::__1::allocator<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> > > >::construct<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >, std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> > >(std::__1::allocator<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> > >&, std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >*, std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >&&) /usr/local/opt/llvm-7.0/bin/../include/c++/v1/memory:1562
    #5 0x62de90 in void std::__1::allocator_traits<std::__1::allocator<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> > > >::__construct_backward<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >*>(std::__1::allocator<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> > >&, std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >*, std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >*, std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >*&) /usr/local/opt/llvm-7.0/bin/../include/c++/v1/memory:1678
    #6 0x62de90 in std::__1::vector<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >, std::__1::allocator<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> > > >::__swap_out_circular_buffer(std::__1::__split_buffer<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >, std::__1::allocator<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> > >&>&) /usr/local/opt/llvm-7.0/include/c++/v1/vector:931
    #7 0x62cd5e in void std::__1::vector<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >, std::__1::allocator<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> > > >::__push_back_slow_path<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> > >(std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >&&) /usr/local/opt/llvm-7.0/include/c++/v1/vector:1615:5
    #8 0x7f80d3b15ea0 in std::__1::enable_if<is_complete_type<rttr::type>::value, rttr::type>::type rttr::detail::create_or_get_type<rttr::type>() (/home/gabyx/Desktop/Repository/ExecutionGraph/build/lib/libExecutionGraph-Core-dbg.so.1.0.3+0x17eea0)
    #9 0x7f80d38f15b1 in _GLOBAL__sub_I_standard_types.cpp (/home/gabyx/Desktop/Repository/ExecutionGraph/build/lib/libExecutionGraph-Serialization-dbg.so.1.0.3+0x5a5b1)
    #10 0x7f80d3bb7989 in call_init /build/glibc-B9XfQf/glibc-2.28/elf/dl-init.c:72:3
    #11 0x7f80d3bb7a88 in call_init /build/glibc-B9XfQf/glibc-2.28/elf/dl-init.c:30:6
    #12 0x7f80d3bb7a88 in _dl_init /build/glibc-B9XfQf/glibc-2.28/elf/dl-init.c:119:5
    #13 0x7f80d3ba80c9  (/lib64/ld-linux-x86-64.so.2+0x10c9)

0x6030000001a8 is located 24 bytes inside of 32-byte region [0x603000000190,0x6030000001b0)
allocated by thread T0 here:
    #0 0x53fba0 in operator new(unsigned long) /home/gabyx/Desktop/Repository/llvm-project/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x62d437 in std::__1::__libcpp_allocate(unsigned long, unsigned long) /usr/local/opt/llvm-7.0/bin/../include/c++/v1/new:252:10
    #2 0x62d437 in std::__1::allocator<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> > >::allocate(unsigned long, void const*) /usr/local/opt/llvm-7.0/bin/../include/c++/v1/memory:1799
    #3 0x62d437 in std::__1::allocator_traits<std::__1::allocator<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> > > >::allocate(std::__1::allocator<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> > >&, unsigned long) /usr/local/opt/llvm-7.0/bin/../include/c++/v1/memory:1548
    #4 0x62d437 in std::__1::__split_buffer<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >, std::__1::allocator<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> > >&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> > >&) /usr/local/opt/llvm-7.0/bin/../include/c++/v1/__split_buffer:311
    #5 0x62c9b2 in void std::__1::vector<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >, std::__1::allocator<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> > > >::__push_back_slow_path<std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> > >(std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >&&) /usr/local/opt/llvm-7.0/include/c++/v1/vector:1611:49
    #6 0x7f80d3b149a0 in std::__1::enable_if<is_complete_type<void*>::value, rttr::type>::type rttr::detail::create_or_get_type<void*>() (/home/gabyx/Desktop/Repository/ExecutionGraph/build/lib/libExecutionGraph-Core-dbg.so.1.0.3+0x17d9a0)

HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_container_overflow=0.
If you suspect a false positive see also: https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow.
SUMMARY: AddressSanitizer: container-overflow /usr/local/opt/llvm-7.0/bin/../include/c++/v1/memory:2624:26 in std::__1::unique_ptr<rttr::detail::type_data, std::__1::default_delete<rttr::detail::type_data> >::release()
Shadow bytes around the buggy address:
  0x0c067fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c067fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c067fff8000: fa fa fd fd fd fa fa fa fd fd fd fa fa fa fd fd
  0x0c067fff8010: fd fd fa fa fd fd fd fd fa fa fd fd fd fd fa fa
  0x0c067fff8020: fd fd fd fd fa fa fd fd fd fd fa fa fd fd fd fd
=>0x0c067fff8030: fa fa 00 00 00[fc]fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8070: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==2662==ABORTING
```

**Comment by acki-m** [comment]
What, does it mean: "container-overflow"?

**Comment by TheAifam5** [comment]
@acki-m https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow

**Comment by gabyx** [comment]
@acki-m : Do you think of any MWE which we could try to reproduce this?
This function seems to make some issue?:
```cpp
rttr::detail::create_or_get_type<rttr::type>()
```

**Comment by gabyx** [comment]
I am wondering about the line: 
`    #8 0x7f80d3b15ea0 in std::__1::enable_if<is_complete_type<rttr::type>::value, rttr::type>::type rttr::detail::create_or_get_type<rttr::type>() (/home/gabyx/Desktop/Repository/ExecutionGraph/build/lib/libExecutionGraph-Core-dbg.so.1.0.3+0x17eea0)
`
How does it make sense that somehow it tries to call
`rttr::detail::create_or_get_type<rttr::type>`
? Isn't that biting into its tail, how can we get the type of `rttr::type`
Is that my error somewhere?

**Comment by gabyx** [comment]
There is actually code, where a `variant`  is instantiated `rttr::variant::variant<const rttr::type &, rttr::type>`
